### ISSUE TITLE
Issue Extracting Firmware

### ISSUE THREAD

**Issue by markmn123** [xchwarze/wifi-pineapple-cloner#11]
Running Ubuntu 22.04 LTS 5.15.0-27-generic in a VM (yay)
I have a netgear R6350 which is pretty close hardware wise to the nano and tetra since it has mipsel_24kc
was hoping to flash with tetra firmware so i can have a wifi pineapple tetra to go with my nano (actually purchased from hak5)
Any help is greatly appreciated. Shoot if this works I might shoot for the Mk IIV!

When trying to extract i get this
user@greyteam:~/Desktop/Firmware$ fmk-tool/extract-firmware.sh tetra_factory.bin 
Firmware Mod Kit (extract) 0.99, (c)2011-2013 Craig Heffner, Jeremy Collake
Preparing tools ...
configure: error: cannot find required auxiliary files: config.guess config.sub
make: *** No targets specified and no makefile found.  Stop.
Tools build failed! Check pre-requisites. Quitting...

list of what i have done....
sudo apt-get update
2  sudo apt-get upgrade
3  sudo apt install build-essential dkms linux-headers-$(uname -r)
4  sudo reboot
5  sudo apt-get isntall virtualbox-guest-additions-iso
6  sudo apt-get install virtualbox-guest-additions-iso
7  sudo reboot
8  sudo ./autorun.sh 
9  ./autorun.sh 
10  sudo reboot
11  sudo apt-get install git
12  git clone https://github.com/rampageX/firmware-mod-kit fmk-tool
13  cd fmk-tool/
14  ./extract-firmware.sh tetra_factory.bin 
15  sudo apt-get install autoconf bison build-essential libssl-dev libyaml-dev libreadline6 libreadline6-dev zlib1g zlib1g-dev
16  sudo apt-get install autoconf
17  ./extract-firmware.sh tetra_factory.bin 
18  autoconf
19  autoconf -version
20  autoconf --version
21  sudo apt install software-properties-common apt-transport-https
22  wget -O- https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc | sudo apt-key add -
23  echo "deb https://packages.erlang-solutions.com/ubuntu focal contrib" | sudo tee /etc/apt/sources.list.d/erlang.list
24  sudo apt-get update
25  sudo apt install erlang
26  sudo apt-get install erlang
27  sudo apt-get install erlang-appmon
28  sudo apt-get install erlang-crypto
29  sudo apt-get install libssl1.1
30  apt search libssl
31  sudo apt-get install libssl
32  sudo apt-get install libssl-dev
33  sudo apt-get install erlang-crypto
34  apt search libssl
35  sudo apt-get install libssl-dev
36  sudo apt-get install libssl1.1
37  sudo apt-get install erlang
38  sudo apt-get install gcc
39  sudo apt-get install perl
40  sudo apt-get install ncurses
41  sudo apt-get install ncurses-dev
42  sudo apt-get install termcap
43  sudo apt-get install termcap-dev
44  sudo apt-get install openssl
45  ./extract-firmware.sh tetra_factory.bin 
46  sudo apt-get isntall binwalk
47  sudo apt-get install binwalk
48  ./extract-firmware.sh tetra_factory.bin 
49  sudo ./extract-firmware.sh tetra_factory.bin 
50  erlang
51  sudo apt-get install erlang
52  sudo apt-get update
53  sudo apt-get upgrade
54  sudo apt-get install erlang-base
55  sudo ./extract-firmware.sh tetra_factory.bin 
56  sudo apt-get install erlang
57  sudo apt-get purge erlang
58  wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb
59  sudo dpkg -i erlang-solutions_2.0_all.deb
60  sudo apt-get update
61  sudo apt-get install erlang
62  sudo ./extract-firmware.sh tetra_factory.bin 
63  cd ..
64  fmk-tool/extract-firmware.sh tetra_factory.bin 
65  sudo apt-get install git build-essential zlib1g-dev liblzma-dev python-magic
66  pip install python-magic
67  sudo apt install python3-pip
68  sudo apt-get install git build-essential zlib1g-dev liblzma-dev
69  sudo apt-get install libmagic1
70  pip install python-magic
71  ls -al
72  fmk-tool/extract-firmware.sh tetra_factory.bin 
73  sudo apt-get install zlib1g-dev
74  gcc
75  sudo apt-get update
76  cd ..
77  sudo nano /etc/apt/sources.list
78  sudo apt-get upgrade
79  sudo reboot
80  cd Firmware/
81  ls -al
82  fmk-tool/extract-firmware.sh tetra_factory.bin

**Comment by xchwarze** [comment]
use binwalk directly
https://github.com/xchwarze/wifi-pineapple-cloner/blob/master/tetra.md
