### ISSUE TITLE
glar300m16 ext pineapple

### ISSUE THREAD

**Issue by patatessss121aq** [xchwarze/wifi-pineapple-cloner#12]
run this code binwalk _tetrafw.bin.extracted/sysupgrade-pineapple-tetra/root -e --preserve-symlinks
binwalk
such an error
I'm buying

General Error: Cannot open file --preserve-symlinks (CWD: /home/k-ali) : [Errno 2] No such file or directory: '--preserve-symlinks'

how can i solve this

**Comment by xchwarze** [comment]
install [Binwalk 2.3.3](https://github.com/ReFirmLabs/binwalk/releases/tag/v2.3.3) version
