### ISSUE TITLE
5ghz info

### ISSUE THREAD

**Issue by BreakSecurity** [xchwarze/wifi-pineapple-cloner#13]
I, first of all thanks for your massive efforts, sad to see people behave badly stealing others works...

I wanna know which setup would you advise me to play with 5ghz too.

As an example tetra with ar300 won't work cause internal chip is only 2.4 and even if I plug a 5ghz chip will be only one, right?

Thanks for your time

**Comment by xchwarze** [comment]
> I, first of all thanks for your massive efforts, sad to see people behave badly stealing others works...
thanks for the words friend!

> As an example tetra with ar300 won't work cause internal chip is only 2.4 and even if I plug a 5ghz chip will be only one, right?
unfortunately it is as you say, the 5ghz wifi will not work.
even connecting a USB 5ghz WiFi adapter you will have problems or at least that happened to me in all my tests

**Comment by xchwarze** [comment]
@BreakSecurity
I rebuild the project with OpenWrt 19.07.7 and buy an adapter based on MT7612U
Only in this way will I be able to use the 5ghz in a stable way!
For more info maybe this doc it could be useful
https://docs.hak5.org/wifi-pineapple/faq/compatible-802.11ac-adapters

**Comment by xchwarze** [comment]
You can download the lastest builds in https://github.com/xchwarze/wifi-pineapple-cloner-builds main branch
