### ISSUE TITLE
jffs2reset sometimes yields ipv6 after setup/reset

### ISSUE THREAD

**Issue by bakabaka** [xchwarze/wifi-pineapple-cloner#15]
Sometimes when doing jffs2reset -y && reboot you get served an ipv6 address (it is unknown to me as of why is this the default behavior at TIMES (although i can see how this could be useful to some)), had to break out the uart dongle to look into it.
This happened to me with the following images multiple times when resetting the mtd:

Images
MD5 (gl-ar300m-pineapple-nano.bin) = 5410eeadab0b134e372c44d1dbb7354f
MD5 (gl-ar150-nano-sysupgrade.bin) = 18235f20129828030ac542f41d9b3080

After some digging the dhcp config file has following options dhcpv6 'server', was changed to dhcpv4 'server'

Ipv6 address at hand with a cellphone yikes.

Thanks for your Great work!

**Comment by xchwarze** [comment]
I think this error is due to firewall rules.
I'm going to play with my ar150 to see if I find a solution

**Comment by bakabaka** [comment]
Quick update, was watching a defcon video and i came across this:
<img width="548" alt="image" src="https://user-images.githubusercontent.com/207563/190253014-847869e3-3ede-4775-821d-c19ddd46b781.png">
This matches the behavior on when resetting the firmware. We get assigned an in that range, so by that logic the dhcp server is not being seen by the clients when connected via wlan/lan.

Here is a link to said video and timestamp: https://youtu.be/rurYRDlf1Bo?t=2337 
I got a device for crafting my cfw and will be posting back if i get some results. So in short, resets seem to make the dhcp server unavailable.

**Comment by xchwarze** [comment]
I think that in this case what can be done is to manually configure the IP to setup the pineapple and restart it.

Maybe you have to do a build with openwrt 19.07.7 or 19.07.10 and see if it still happens.
Although the Karma patches may not work on 19.07.10
