### ISSUE TITLE
i uploaded, i'm entering from ip but it's empty

### ISSUE THREAD

**Issue by patatessss121aq** [xchwarze/wifi-pineapple-cloner#18]
i uploaded, i'm entering from ip but it's empty

**Comment by xchwarze** [comment]
All the builds I do I test on an ar150 and an arches C7 so what is uploaded is tested.
Anyway if you want me to help you:
1) tell me the exact router model and
2) record with OBS Studio or some other program as you are installing it.

Remember that before installing this fw you have to install openwrt 19 on the router and then follow the rest of the documentation steps.

Any step you do wrong causes it to not work or even break the router.

**Comment by patatessss121aq** [comment]
solved it but i can't load module?

**Comment by xchwarze** [comment]
from docs
```
Remember that...
* If you are going to use this on hardware with a single wifi adapter you have to add a second.
* If your hardware has less than 32 megabytes of space you have to use a pendrive.
* The pendrive has to be formatted from the pineapple panel `Advanced > USB & Storage > Format SD Card`.
* When pineapple starts it will run the 20-sd-universal script and install the missing packages on the pendrive from internet.
```

**Comment by MDRafi08642** [comment]
@patatessss121aq 
how to solve blank webpage problem? (on http://172.16.42.1)
