### ISSUE TITLE
Pineapple PineAP giving signal but not giving connection to clients

### ISSUE THREAD

**Issue by timkatta5** [xchwarze/wifi-pineapple-cloner#21]
I recently installed wifi pineapple on my Gl inet AR 750.  I mounted the sd card and installed modules on it and the installation went well. I installed an external adapter to give it an external connection. After that I started PineAP and it started giving wifi signals of multiple wifis. The issue with the pineapple is that it does not give a connection to the users it only gives a signal of multiple wifi networks, when I try to connect to them I get an error from the device : "unable to join the network" I tried it on android, windows and iphone, all gave me same result. My filters are correctly set to deny for both and the lists are empty. I have been having this problem since day one, I have reset the pineapple twice, formated the sd card twice, and tried every solution I could think of and it did not work. I attached the log files here. 

[dmseg.txt](https://github.com/xchwarze/wifi-pineapple-cloner/files/14911112/dmseg.txt)
[Pineapple log.txt](https://github.com/xchwarze/wifi-pineapple-cloner/files/14911113/Pineapple.log.txt)
[Sat Apr  6 221149 2024 daemon.notic.txt](https://github.com/xchwarze/wifi-pineapple-cloner/files/14911114/Sat.Apr.6.221149.2024.daemon.notic.txt)
![image](https://github.com/xchwarze/wifi-pineapple-cloner/assets/109509209/e004ed20-8e6d-4c90-96c4-cea3253b4cf5)

On a side note, I was wondering if it was possible to connect from distance to the wifi pineapple, for instance it if is running and turned on with an internet connection, can I connect to the admin panel from distance similar to C2 - HAK5 CLOUD COMMAND AND CONTROL , it doesnt have to be like theirs, it can be via tunneling or openvpn , but either way could you tell me how to do it.

**Comment by xchwarze** [comment]
I am confused by the use of the word "pineapple" in the sentences. I guess you mean the PineAP used in attack mode...? From the way you describe it I understand you mean you are using the KARMA attack and the clients do not connect or (if they connect they are not given internet).

Is that what is happening?

**Comment by timkatta5** [comment]
Yes I mean PineAP used in attack mode. Karma is showing many wifi networks but my device are not getting a connection from the network (I am not talking about internet , I am talking about entering the network as a user, its similar to when you input a wrong password to a wifi and you get rejected, only difference is that they are open networks and I get message: unable to join)

**Comment by xchwarze** [comment]
Cell phones normally disconnect the wifi network if they do not detect internet.
So it would be necessary to deactivate that and determine if LAN it works correctly.

**Comment by timkatta5** [comment]
My laptop is plugged via ethernet to the GL-inet750, the connection has internet if that's your comment, unless there is another way to detect if the LAN works correctly?

**Comment by xchwarze** [comment]
I understand that when a victim connects to the ip given by the router to port 80, nginx should receive it in order to be able to do captive portal attacks and so on.
If you log in as a victim does that happen...?

I want to understand if the network connection is established and working properly. Anyway at most the only thing I can do is downgrade the OpenWRT version to the original pineapple version, but everything that is 5g wifi works fatal on that branch....

**Comment by timkatta5** [comment]
I uploaded a video demonstrating it. The captive portal attack only works when I am logging into the open ssid "Alooooha" I set up in network, I cant seem to get access as a victim to the network during Karma attack. I currently have installed the OpenWRT 19.07.7. 
For me 5g is not important, but most people would definitely disagree with me.

**Comment by xchwarze** [comment]
Download this and then use the delete link, they are builds made with the same version as the original hard so it should work the same as if you had it...

download
https://www.sendspace.com/file/kdicma

delete
https://www.sendspace.com/delete/kdicma/918bbcf4daa54866e9d9df79e82a19f9

**Comment by xchwarze** [comment]
Repite las pruebas con ese build. Serian las mismas versiones que el original pero con todas mis mejoras.
Eso si seguramente ya no puedas usar wifi en 5g

**Comment by xchwarze** [comment]
Repeat the tests with this build. It would be the same versions as the original but with all my improvements, but you will probably not be able to use wifi on 5g.

**Comment by timkatta5** [comment]
I installed it and deleted the file from the site, I tested on 4 devices: 2 android phones, 1 iphone , 1 windows laptop. Only 1 android successfully connected to a PineAP network, all the rest gave me the same error I had before. 

I got one pop up message from iphone that the network I am trying to connect uses same mac address as other networks so I it is suspicious. 
I got a sign on the android phone which connected the first time, when I tried to connect the second time: network out of range

**Comment by xchwarze** [comment]
What version of android does that cell phone have and what model is it? The original version that you had installed did not connect to that cell phone?

**Comment by timkatta5** [comment]
Phone is a Rooted One Plus 7 pro using android Oxygen OS 10.3.8. It is similar for both versions I installed, the one plus phone would connect once in a lifetime to that phone, other devices it would not connect ever.

**Comment by xchwarze** [comment]
I guess in reality it is that this version of KARMA is not as effective in modern times since there is no technical reason for it to work differently on the "real" hardware and the one you are using.
