### ISSUE TITLE
Nothing happens when i try install module

### ISSUE THREAD

**Issue by baronor** [xchwarze/wifi-pineapple-cloner#23]
A try of installing of module causes displaying  a window with info" Downloading module, please wait", and nothing happens.
I have Internet at the device, the Page with News at Dashoboard is loaded correctly,  after i click get modules i have a list modules to install. This concers any modules. Model of my router is TP-LINK Archer C7 v4.
![tetoc1](https://user-images.githubusercontent.com/69898623/196243273-1637fec8-7dfe-4fcb-ba0e-ef9672671ee9.png)

**Comment by xchwarze** [comment]
Fixed in lastest builds
