### ISSUE TITLE
Problem with running of modules

### ISSUE THREAD

**Issue by baronor** [xchwarze/wifi-pineapple-cloner#24]
There is problem with running of some of modules. At this moment is identified identical problem at two modules:

- Occupinaple 
- Deauth

After i start running these module there is only information in log that module is starting and nothing happen.
![occupinaple](https://user-images.githubusercontent.com/69898623/196385784-c1c8c494-6e9c-4ba2-91c2-0f37d909915a.png)

For module 

- Nmap 

there is no button to install as on screenshot.
![nmap1](https://user-images.githubusercontent.com/69898623/196385903-20a687d5-5bb8-4f5f-8814-85fdec17950a.png)

My model is TP-Link Archer C7 v4.

**Comment by xchwarze** [comment]
are you running the modules from a usb drive?
I guess not since those buttons are hidden based on what you have connected and if it has enough space

**Comment by xchwarze** [comment]
I remade the entire panel and the two modules that I used the most because the code and the quality in general were garbage... so it could be anything.
You would have to debug what is failing and if you find a solution send the pr to the modules repo.
