### ISSUE TITLE
Flashing firmware does not seem to go right

### ISSUE THREAD

**Issue by ariary** [xchwarze/wifi-pineapple-cloner#25]
Hi xchwarze!

I am a bit struggling to flash my router with pineapple firmware. And I am a bit confused on where is the issue and/or how to spot it

I have a gl-750s-ext as recommended, when I flash the firmware nothing really fancy happens.

Find below my steps to reproduce

## Steps to reproduce
1. Buy a gl-750s
2. Power on the router, once done connect to it using ssh
3. Transfer the firmware file ( [this one](https://github.com/xchwarze/wifi-pineapple-cloner-builds/blob/main/releases/gl-ar750s-universal-sysupgrade.bin)) using scp
4. With ssh session, Flash the firmware `sysupgrade -n -F [FIRMWARE_FILE_BIN]

From now, my ssh connection is closed (logical), I wait a bit (how many times I have to?) and after a moment I can only see the « power » light of the gl-750s which is on (2G and 5G are light off).

**BUT** no new wifi network shows up. I try  to plug also the Ethernet cable but still unable to join `172.16.42.1ˋ

 I don’t know how to monitor what is going on.

Also maybe I have to perform some specific manipulation with the gl-750s before/during/after flashing ?

## Additional notes
* I am flashing the device from a windows machine (with wsl)
* I have also try to flash firmware using the web admin panel but it is the same thing

**Comment by xchwarze** [comment]
My gl-ar750s hasn't arrived yet so I can't play it yet.
You would have to connect it by serial and pass me the log here.

**Comment by xchwarze** [comment]
these links may help you to connect to the serial console
https://docs.gl-inet.com/en/3/dev/serial/
https://openwrt.org/toh/gl.inet/gl-ar750s

**Comment by ariary** [comment]
Thanks for the resources and prompt response !
Need to get some materials hence before using serial console

.. Don't hesitate to share when you'll receive yours

**Comment by ariary** [comment]
My bad!

Upload the firmware from uboot panel and it will work like a charm! (now some pineapple setup issue but I'm enthusiast about it)

thank's for the work
