### ISSUE TITLE
Is there a possibility to get the tool to be able to do its magic with pineapple mark7 firmware?

### ISSUE THREAD

**Issue by junziii** [xchwarze/wifi-pineapple-cloner#27]
Dear xschwarze,

do you think the "move" in the Title is possible? I try for upgrading my old tetra to the newer pineapple mark7 software without mentionable success..

Any tips or pointings to me?

Thanks for your project and in advance!

junz

**Comment by xchwarze** [comment]
The mk7 is quite abandoned. It seems that no one uses it...
So I don't see any reason to do something like that other than seeking to be denounced by a company (and that this project be deleted for it)
The tetra doesn't even have enough memory to run the mk7.
