### ISSUE TITLE
GL.Inet Slate

### ISSUE THREAD

**Issue by gmoeller54** [xchwarze/wifi-pineapple-cloner#28]
Hi there - I would like to support the cloning onto a GLInet Slate 
There are 2 new versions of the slate.   I've been included in their beta testing and have an extra unit I could send.
How is it best to communicate?
Thx

**Comment by xchwarze** [comment]
GL Inet's attitude towards OpenWrt is completely idiotic.
1. They do not integrate their products to the stable branches
2. They don't use gpl drivers
3. They do not send improvements
They basically don't do anything to help, but they use as much of OpenWrt as they can.

If you use the Imagebuilders here https://github.com/gl-inet-builder you can have several models running with my project.
For example the mt1300.
As for the other models that you mention, I don't know if they have support in OpenWrt 19, the mt1300 would have it using the glinet imagebuilder.
