### ISSUE TITLE
How to install module on pendrive?

### ISSUE THREAD

**Issue by aoxo2022** [xchwarze/wifi-pineapple-cloner#29]
![20221129_102556](https://user-images.githubusercontent.com/101029515/204431350-7e8ed2e6-7948-47c0-90d2-4eb3541fcc72.jpg)

![20221129_102748](https://user-images.githubusercontent.com/101029515/204431587-3405a11e-1b4d-49a1-a5fe-3f887d18b583.jpg)

Can you help me?

**Comment by xchwarze** [comment]
you have to format the pendrive/sd through the panel option.

**Comment by aoxo2022** [comment]
> you have to format the pendrive/sd through the panel option.

already sir, but still no option appears to install on the sd card

**Comment by xchwarze** [comment]
try running the commands manually
https://github.com/xchwarze/wifi-pineapple-panel/blob/wpc/src/pineapple/modules/Advanced/formatSD/format_sd

as long as the condition of the two partitions in the usb is met, it will be mounted correctly.
You can even create a single fat partition and it should mount fine to install files (but in that case the swap part wouldn't work).
