### ISSUE TITLE
Stuck on boot cant ssh

### ISSUE THREAD

**Issue by dacigm007** [xchwarze/wifi-pineapple-cloner#30]
Ok so i installed everything set password on openwrt and saved it now i get stuck on boot and when i try to ssh in its says that password is incorrect

**Comment by xchwarze** [comment]
You are not really giving any information to be able to help you....
But everything seems to indicate that:
A) you did not follow the installation steps
B) your router model does not have a reset button

I understand that there should be no case in the current version where what is mentioned in B happens, so I recommend you re-install following the steps.

**Comment by dacigm007** [comment]
ok so i figured out that i didnt put password while installing wrt my router model is archer c5 v1 and now i have no way to reset it i tried with pineapple firmware with that recovery page but its blank do you have any advice what should i do because now evferything "works" but i dont have password and i cant reinstall open wrt and do it again
