### ISSUE TITLE
some errors on wifi pineapple

### ISSUE THREAD

**Issue by MDRafi08642** [xchwarze/wifi-pineapple-cloner#32]
Router: Netgear r6120
There's some errors on wifi pineaple...
can you solve it?
![Screenshot 2022-12-04 075338](https://user-images.githubusercontent.com/81744420/205471322-61e41887-56a9-4f34-b922-de3fb59f6baa.png)
![Screenshot 2022-12-04 075635](https://user-images.githubusercontent.com/81744420/205471327-eaeae692-ca20-482d-ade0-c5f2ef28971f.png)
![Screenshot 2022-12-04 082234](https://user-images.githubusercontent.com/81744420/205471356-20905a9e-6b91-4af3-80ae-6e369cebcc32.png)

**Comment by xchwarze** [comment]
the same errors happen on the original hardware. In any case, they do not cause any errors in the equipment
