### ISSUE TITLE
Recon scan & Terminal doesn't work

### ISSUE THREAD

**Issue by MDRafi08642** [xchwarze/wifi-pineapple-cloner#33]
Router: Netgear r6120
After installing wifi pineapple bin,
Recon scan & pmkid scan doesn't work...
(Other scans like- wps,client mode perfectly working)
Also Terminal doesn't work...
![Screenshot 2022-12-04 082420](https://user-images.githubusercontent.com/81744420/205471532-d20cec0b-8d95-4717-a791-3a25f8cfc2d5.png)

![Screenshot 2022-12-04 080001](https://user-images.githubusercontent.com/81744420/205471550-893dd4cc-b848-45d0-b3c6-9e0a982f2ba1.png)

**Comment by xchwarze** [comment]
scan bug) I tried on the gl-ar750s and no defects appeared. Perhaps you tried to use live mode without having the dependencies installed.
terminal bug) Fixed in version 1.2

**Comment by MDRafi08642** [comment]
Thanks. Now terminal working
![Screenshot 2022-12-06 172046](https://user-images.githubusercontent.com/81744420/205898951-b0bb3b9f-e5f2-4463-8126-aee01ed480f8.png)

**Comment by APToni** [comment]
> Маршрутизатор: Netgear r6120 После установки Wi-Fi pineapple bin сканирование Recon и сканирование pmkid не работает... (другие сканирования, такие как wps, клиентский режим работают отлично) Также терминал не работает... ![Скриншот 04.12.2022 082420](https://user-images.githubusercontent.com/81744420/205471532-d20cec0b-8d95-4717-a791-3a25f8cfc2d5.png)
> 
> ![Скриншот 2022-12-04 080001](https://user-images.githubusercontent.com/81744420/205471550-893dd4cc-b848-45d0-b3c6-9e0a982f2ba1.png)

Did you get Recon to work? It doesn't work for me at 150.

**Comment by xchwarze** [comment]
> 
> Did you get Recon to work? It doesn't work for me at 150.

from install and download docs:
* When pineapple starts it will run the `20-sd-universal` script and install the missing packages on the pendrive from internet.

the live scan mode only works if you have python installed.
If you use the timed modes they work fine.

**Comment by MDRafi08642** [comment]
> > Маршрутизатор: Netgear r6120 После установки Wi-Fi pineapple bin сканирование Recon и сканирование pmkid не работает... (другие сканирования, такие как wps, клиентский режим работают отлично) Также терминал не работает... ![Скриншот 04.12.2022 082420](https://user-images.githubusercontent.com/81744420/205471532-d20cec0b-8d95-4717-a791-3a25f8cfc2d5.png)
> > ![Скриншот 2022-12-04 080001](https://user-images.githubusercontent.com/81744420/205471550-893dd4cc-b848-45d0-b3c6-9e0a982f2ba1.png)
> 
> Did you get Recon to work? It doesn't work for me at 150.

NO, scan's doesn't work for me...
And there are some errors while running "20-sd-universal" script ):
Does it for work for you?

**Comment by MDRafi08642** [comment]
> > Did you get Recon to work? It doesn't work for me at 150.
> 
> from install and download docs:
> 
> * When pineapple starts it will run the `20-sd-universal` script and install the missing packages on the pendrive from internet.
> 
> the live scan mode only works if you have python installed. If you use the timed modes they work fine.

yeah, there are errors while running "20-sd-universal" script.
maybe python installation failed !
please, provide instructions to install PYTHON manually.

**Comment by xchwarze** [comment]
Not all routers work the same way so there is a recommended setup based on the hard that is sold today and that everyone can buy.
However, the notes section in the download repo is intended to help you find out what is wrong in each case.

from https://github.com/xchwarze/wifi-pineapple-cloner-builds
![image](https://user-images.githubusercontent.com/2120205/211973230-c26e8fbd-4d07-451b-8b9f-6b4551eb45ec.png)

```bash
opkg update && opkg --dest sd install python-logging python-openssl python-sqlite3 python-codecs && python -m compileall
```
