### ISSUE TITLE
Failed to connect to hostapd

### ISSUE THREAD

**Issue by MDRafi08642** [xchwarze/wifi-pineapple-cloner#34]
Router model: netgear r6120
there's an error, "Failed to connect to hostapd - wpa_ctrl_open: No such file or directory"
Maybe that's why scans doesn't work.
![Screenshot 2022-12-06 172305](https://user-images.githubusercontent.com/81744420/205899946-4e56553c-a709-4de5-b15f-60a7ecdce61c.png)

**Comment by xchwarze** [comment]
It seems that there is some problem with the karma patches, but I already tried in two different routers and everything works correctly.
I recommend you to manually build and comment the karma patch block.

Tested on:
Xiaomi MiWiFi 3G v1 from release repo: works ok
Xiaomi MiWiFi 3G v1 from release master: works ok
GL.iNet GL-AR750S v1 from release repo: works ok
GL.iNet GL-AR750S v1 from release master: works ok
