### ISSUE TITLE
[MODULES][MIPSEL] DWall module problems

### ISSUE THREAD

**Issue by BrianBechtel** [xchwarze/wifi-pineapple-cloner#35]
Clicking enable does not respond, there will be no start listening     XIaomi Router 3G

**Comment by xchwarze** [comment]
You should debug and see what is wrong and if it can be fixed.
Maybe that module doesn't even work in the mipsel version of the project.

**Comment by xchwarze** [comment]
@BrianBechtel From what I saw the module developer hardcoded the path where the binary used for the sniffer is.
If you change that line and maybe some other lines it should work correctly.
