### ISSUE TITLE
how to build for router not supported in 19.07.7

### ISSUE THREAD

**Issue by asmitthapa72** [xchwarze/wifi-pineapple-cloner#37]
as routers supported in openwrt 19.07.7 are not available in my country. how can I build this firmware in newer version of openwrt

**Comment by xchwarze** [comment]
You can:
1) Buy recomended router in Glinet page in AliExpress
2) Use Grabr.io or another similar page
3) Try to use the Karma files from the mk7 although this could only be done in MIPSEL
4) Do a manual build without Karma following the guidelines mentioned in the documentation
5) Backport the router from the new branch to the old 19.07.7
