### ISSUE TITLE
Sim card not detected in GL-X750 (Spitz)

### ISSUE THREAD

**Issue by RickSisco** [xchwarze/wifi-pineapple-cloner#37]
### Current behavior

Sim Card is not detected

### Expected behavior

GL-X750 (Spitz) has a sim slot, but installing a sim does not bring up any setting options

### How to reproduce?

Install a sim card and attempt to set up a honeypot

### What have you tried so far?

ran the Missing_Packages command
Installed sim card and searched all options and menus to set up the sim/modem to connect router to data plan.

**Comment by xchwarze** [comment]
This is beyond the scope of this project and its issues.
Most likely what is happening to you is that your router needs extra dependencies installed that for some reason are not listed in the default declaration. You should see what they are and install them manually,
