### ISSUE TITLE
5ghz adapter

### ISSUE THREAD

**Issue by aoxo2022** [xchwarze/wifi-pineapple-cloner#38]
hallo, iam again

i bought TP-Link Archer T2U Plus
i try this [https://github.com/nlkguy/archer-t2u-plus-linux] cant install

can you help me?

**Comment by xchwarze** [comment]
the only recomended usb wifi stick for 5ghz in openwrt 19 is with MT7612U chipset

**Comment by aoxo2022** [comment]
tq
