### ISSUE TITLE
Starting loop on a Linkit Smart 7688

### ISSUE THREAD

**Issue by alexxr6** [xchwarze/wifi-pineapple-cloner#40]
Hello,

I followed the building process on a fresh installed Ubuntu virtual machine and I changed two things on the process : 

- On step 3 "Generate openwrt extra files" I changed the `tools/fs-patcher.sh rootfs nano` command to `tools/fs-patcher.sh mipsel nano rootfs`
- On step 4 "Build your own build" I edited the ./include/prereq-build.mk file to remove the GCC and G++ version check (GCC 11 and G++ 11 was not detected well) so I was able "make" the image without error.

Once the image was generated, I uploaded it via `scp` and launched the update commande.
The system rebooted after the flash process but keep rebooting.

Flashing process : 
`root@OpenWrt:/# sysupgrade -n -F /tmp/gl-ar150-pineapple-nano.bin`
`Image metadata not found`
`Image check failed but --force given - will update anyway!`
`Commencing upgrade. Closing all shell sessions.`
`Watchdog handover: fd=3`
`- watchdog -`
`killall: telnetd: no process killed`
`killall: can't kill pid 1367: No such process`
`Sending TERM to remaining processes ... ntpd hostapd`
`dnsmasq ubusd urngd logd rpcd netifd odhcpd uhttpd`
`Sending KILL to remaining processes ...`
`Switching to ramdisk...`
`Performing system upgrade...`
`Unlocking firmware ...`

`Writing from <stdin> to firmware ...`
`Upgrade completed`
`Rebooting system...`
`umount: can't unmount /dev: Resource busy`
`umount: can't unmount`
`[  263.716526] reboot: Restarting system`
` /tmp: Resource busy`

And after rebooting : 
`## Booting image at bc050000 ...`
`   Image Name:   MIPS OpenWrt Linux-4.14.171`
`   Image Type:   MIPS Linux Kernel Image (lzma compressed)`
`   Data Size:    1586412 Bytes =  1.5 MB`
`   Load Address: 80060000`
`   Entry Point:  80060000`
`   Verifying Checksum ... OK`
`   Uncompressing Kernel Image ... OK`
`No initrd`
`## Transferring control to Linux (at address 80060000) ...`
`## Giving linux memsize in MB, 128`

`Starting kernel ...`

`## Control returned to monitor - resetting...`
`                                             [04040D08][04040D08]`
`DDR Calibration DQS reg = 00008A8A`

`#NEW BOOT#`
`U-Boot 1.1.3 (Dec  6 2016 - 11:20:23)`

Does I missed something about this specific model, which appears as compatible?

Kind regards,
Alexandre

**Comment by xchwarze** [comment]
hi!
Try doing a common openwrt build and see installing the dependencies in batches.
I guess the problem is in the FS.
The hard gives you to run the tetra so also try with that flavor.

**Comment by alexxr6** [comment]
I tried with tetra : 
This build step
`tools/builder.sh mips tetra imagebuilder-19.07.7-ar71xx-generic gl-ar750s`
This firmware download
`# tetra
`#wget https://www.wifipineapple.com/downloads/tetra/latest -O basefw.bin`
`#binwalk basefw.bin -e `
`#binwalk _basefw.bin.extracted/sysupgrade-pineapple-tetra/root -e --preserve-symlinks`
`#mv _basefw.bin.extracted/sysupgrade-pineapple-tetra/_root.extracted/squashfs-root/ rootfs-base`
Copying the right pineapple files
`tools/copier.sh lists/tetra.filelist rootfs-base rootfs`
And fixing the files : 
`tools/fs-patcher.sh mips tetra rootfs`

But I still get the loop booting problem.

I also tried to use the working OpenWRT firmware but still get the same issue.

To install the dependencies I must use the internal package manager?
There is no ethernet port on this device so I can only import the dependencies one by one.

Kind regards,
Alexandre

**Comment by xchwarze** [comment]
You would have to check which version of OpenWrt is functional to build on that device.
Once you have that figured out you would have to see how viable it is to use these tools on that version to generate the fw.
If 19.07.7 generates a valid fw you should have no problem using this repo.
