### ISSUE TITLE
How to build for 211 devices supported by the project?

### ISSUE THREAD

**Issue by APToni** [xchwarze/wifi-pineapple-cloner#41]
For example Smartbox GIGA
For him, there is only a snapshot from 22 openwrt. The description says that it supports Pineapple. In your questions, you suggest:
1. Buy recommended router in Glinet page in AliExpress
2. Use Grabr.io or another similar page
3. Try to use the Karma files from the mk7 although this could only be done in MIPSEL
4. Do a manual build without Karma following the guidelines mentioned in the documentation
5. Backport the router from the new branch to the old 19.07.7

Let's say points 1 and 5 are more understandable, and points 2, 3, 4 are not entirely clear. Can you make more detailed instructions for problematic routers (for example Smartbox GIGA)?

**Comment by xchwarze** [comment]
The list of compatible devices is made with the data provided by OpenWRT. The filtering criteria were that they are supported by OpenWRT 19 and that they have the same capabilities as the original hard.
Knowing this, there are two scenarios:
1) OpenWRT data may be incorrect for some devices.
2) If we change the criteria, the devices become many more, more than 500.

**Comment by APToni** [comment]
Smartbox GIGA? Can you make more detailed instructions for problematic router.

**Comment by xchwarze** [comment]
The options you have in such a case are:
1. Buy a compatible router using Aliexpress or Grabr.io. Both are shopping sites where you can buy something compatible from all over the world.
2. Make a custom build for your hard. Basically it could cover points 3, 4 and 5 of the list you copied. If you did not understand what I put in those points is because you can not really do that because you have to have some training in what is embedded and linux making/development.

**Comment by APToni** [comment]
Good afternoon, you can provide instructions or a ready-made bean for beeline turbo +
What you offer to buy has not been on sale for a long time, on Ali there are scammers, one-day shops.

**Comment by xchwarze** [comment]
this is the oficial store: https://es.aliexpress.com/store/5100113
I bought several routers and they all arrived in perfect condition and at a better price than Amazon

**Comment by xchwarze** [comment]
At the end of December I went in to buy some 750 more and they had stock, they must have run out these days.
Buy any that have those modern micros and that amount of memory.
Maybe a used Archer C7 is the best option.
