### ISSUE TITLE
Building for a Western Digital My Net N750

### ISSUE THREAD

**Issue by dake8** [xchwarze/wifi-pineapple-cloner#44]
Hey, first thank you for this Great Project..
is there a step by step guide that even a noob understands? 
unfortunately, I lack a little time, because I am my 2 sick children in the care.
thank you

**Comment by xchwarze** [comment]
I understand that these are the steps for your hardware:

```
chmod +x tools/*.sh
tools/dependencies-install.sh openwrt-deps-mips
sudo tools/dependencies-install.sh ubuntu-deps
tools/builder.sh mips universal imagebuilder-19.07.7-ar71xx-generic mynet-n750
```

The steps are for ubuntu 18 or 20. If you use ubuntu 22 you will surely have to do some more steps.
You can install virtual box and use a ready made vm. There are pages where you can download them:
https://www.osboxes.org/ubuntu/
https://www.linuxvmimages.com/images/ubuntu-2004/

**Comment by logm1lo** [comment]
> I understand that these are the steps for your hardware:
> 
> ```
> chmod +x tools/*.sh
> tools/dependencies-install.sh openwrt-deps-mips
> sudo tools/dependencies-install.sh ubuntu-deps
> tools/builder.sh mips universal imagebuilder-19.07.7-ar71xx-generic mynet-n750
> ```
> 
> The steps are for ubuntu 18 or 20. If you use ubuntu 22 you will surely have to do some more steps. You can install virtual box and use a ready made vm. There are pages where you can download them: https://www.osboxes.org/ubuntu/ https://www.linuxvmimages.com/images/ubuntu-2004/

But is the tools the same versions or can you build it with newer tools like the cpp compiler?

**Comment by xchwarze** [comment]
You can have more than one version of the compiler installed on the machine. When I referred to "more steps" for that case it was for that kind of thing.
Anyway you can always do it in a vm with an old version of ubuntu.
