### ISSUE TITLE
http://172.16.42.1:1471/ won't open on ASUS AC51U

### ISSUE THREAD

**Issue by CatalinHorosanu** [xchwarze/wifi-pineapple-cloner#45]
I have followed the steps and made them all but http://172.16.42.1:1471/ isn't loading. Neither ssh root@172.16.42.1.
The router's light are on and from time to time blinking.
From OpenWrt I could ping 8.8.8.8 but couldn't make updates (failed to download) so I have attached an USB drive but couldn't map it(nothing regarding this can be found on OpenWrt interface.

Any ideas? Might be that it doesn't have enough storage to boot?

**Comment by xchwarze** [comment]
if you made a custom build I ask you to upload the generated fw so I can check it

**Comment by CatalinHorosanu** [comment]
I used your version. Had openwrt 07.7, did scp and the connection closed and after that I had 4 leds open all the time and sometimes they would  blink. Waited for 40-50 min and every time I would try to ssh into it it just waits and then it gives connection timeout. I am able to ping google from openwrt but can't download the necessary packages in order to add the usb as storage. I only have a tp-link TL-WN722N as adapter. Maybe I should try connecting a ethernet cable from my main router to this one in order to do the updates and add usb as storage? It's strange that it doesn't want to ssh into it after I add your version. Tried 4 times, installed openwrt again and then scp your instalation but it was the same every time.

**Comment by xchwarze** [comment]
I Checked the build and it seems to be well done.
You should connect to ssh using the "root" user and "root" as password and check what might be wrong.
First check if the /pineapple folder exists and if commands like airmon-ng and pineapd exist.

**Comment by CatalinHorosanu** [comment]
Bought an Archer C7 v5 today, will try on both

**Comment by CatalinHorosanu** [comment]
Can't find 19.07.7 OpenWrt for Archer C6 v5. 

Can't get internet access in OpenWrt from AC51U so can't get the packages needed to add the USB as storage. 

I just wasted too much time, Wasted money also on those routers.

Can you make a step-by-step video on any of those routers? (archer c6 or ac51u)

**Comment by xchwarze** [comment]
1. if you have no console or ssh, the fw is not installed.
2. if you don't have ssh the only way to debug is by serial, you should start from there. anyway everything indicates that you are doing something wrong and the fw never installs. 
3. the supported router is the c7 you mentioned yesterday and not the c6 you mention now, the complete list is here https://github.com/xchwarze/wifi-pineapple-cloner/blob/master/devices.md

**Comment by CatalinHorosanu** [comment]
Ok I have made all the updates on AC51U, enabled internet, made the opkg updates, enabled usb 8gb, used the rt-ac51u-universal-sysupgrade.bin, got the commercial upgrade, closing all shell sessions, but 172.16.42.1:1417 can't be reached and ssh to 172.16.42.1 gives connection timed out

**Comment by CatalinHorosanu** [comment]
Ok now it works :d but the initial screen ia stuck on "secure setup disabling wifi is recommended for initial setup"

**Comment by CatalinHorosanu** [comment]
Should I press the router's restart button?

**Comment by xchwarze** [comment]
Yes, and if the router does not have a reset hat button, press the WPS button

**Comment by CatalinHorosanu** [comment]
It works, everything is as expected. The issue was that I didn't remove the static ip from ipv4 after installing openwrt and your issue. Remember this for future issue for those who can't load the page. Cheers!

**Comment by CatalinHorosanu** [comment]
Hello. I haven't used it for a while and changed my internet connection. How can I enter into it to change the internet credentials? Can't ssh on 172.16.42.1
