### ISSUE TITLE
Device lost connection after last upgrade

### ISSUE THREAD

**Issue by martin-arg** [xchwarze/wifi-pineapple-cloner#46]
I upgrade from 2.8.5 to 2.9 in my TP Link C7 V5 router. The last message was that the firmware was download, and was installing but never change, and now I can't connect to the device. After reading the documentation, I'm not sure how to proceed.

**Comment by xchwarze** [comment]
I understand that in those cases you would have to:
A) Do a hard reset to the router to clean the persistence and start as factory
B) Enter recovery mode and load the firmware manually from there
