### ISSUE TITLE
Building for 8MB flash devices - [TP-Link Archer D50 v1]

### ISSUE THREAD

**Issue by NetviperZ** [xchwarze/wifi-pineapple-cloner#56]
First of all  thank you for this interesting project!

So when i try to compile an image for my Archer D50 v1 it return me an error `"file-system partition is too big"` which was expected given the 8Mb small flash size, so i've made a custom build and kept only the minimum packages to mount the usb drive at booting :

`make image PROFILE=tplink_archer-d50-v1 PACKAGES="block-mount kmod-fs-ext4 e2fsprogs kmod-usb-storage busybox openssh-server openssh-sftp-server ca-certificates -wpad-basic -dropbear -odhcpd-ipv6only -ppp -ppp-mod-pppoe" FILES="../build/rootfs" BIN_DIR="../build/release"`

and install the rest after with : `service wpc-tools missing_packages` 

The problem here is that when i try to access the web interface http://172.16.42.1:1471/  i get this error : "ERR_CONNECTION_REFUSED"

On the other hand I manage to access by ssh and I have successfully done injection and monitoring tests with airodump and aireplay but when I try with pineap it doesn't seem working and even karma won't  start:

```
root@Pineapple:~# service pineapd start
Status: OK

root@Pineapple:~# pineap karma on
Failed to connect to hostapd - wpa_ctrl_open: No such file or directory

root@Pineapple:~# pineap handshake_capture_start B4:B0:24:B0:88:20 2
root@Pineapple:~# pineap get_status
{
        "captureRunning": true,
        "bssid": "B4:B0:24:B0:88:20"
        "scanRunning": false
}
```
i'm also using the serial connection for debug  if this can help further ...
I've uploaded the compiled image

thanks in advance!

`Installed Packages:`
> root@Pineapple:~# opkg list-installed
> at - 3.1.23-2
> ath10k-firmware-qca988x-ct - 2020-07-02-1
> autossh - 1.4g-1
> base-files - 204.2-r11306-c4a6851c72
> bash - 5.0-4
> block-mount - 2020-05-12-84269037-1
> busybox - 1.30.1-6
> ca-bundle - 20200601-1
> ca-certificates - 20200601-1
> chat - 2.4.7.git-2019-05-25-3
> dnsmasq - 2.80-16.3
> dropbear - 2019.78-2
> e2fsprogs - 1.44.5-2
> ethtool - 5.2-1
> firewall - 2019-11-22-8174814a-3
> fstools - 2020-05-12-84269037-1
> fwtool - 2
> getrandom - 2019-06-16-4df34a4d-4
> hostapd-common - 2019-08-08-ca8c2bd2-8
> hostapd-utils - 2019-08-08-ca8c2bd2-8
> ip6tables - 1.8.3-1
> iptables - 1.8.3-1
> iw - 5.0.1-1
> iw-full - 5.0.1-1
> iwinfo - 2019-10-16-07315b6f-1
> jshn - 2020-05-25-66195aee-1
> jsonfilter - 2018-02-04-c7e938d6-1
> kernel - 4.14.221-1-b84a5a29b1d5ae1dc33ccf9ba292ca1d
> kmod-ath - 4.14.221+4.19.161-1-1
> kmod-ath10k-ct-smallbuffers - 4.14.221+2019-09-09-5e8cd86f-1
> kmod-ath9k - 4.14.221+4.19.161-1-1
> kmod-ath9k-common - 4.14.221+4.19.161-1-1
> kmod-cfg80211 - 4.14.221+4.19.161-1-1
> kmod-crypto-aead - 4.14.221-1
> kmod-crypto-crc32c - 4.14.221-1
> kmod-crypto-hash - 4.14.221-1
> kmod-crypto-manager - 4.14.221-1
> kmod-crypto-null - 4.14.221-1
> kmod-crypto-pcompress - 4.14.221-1
> kmod-dnsresolver - 4.14.221-1
> kmod-eeprom-93cx6 - 4.14.221-1
> kmod-fs-ext4 - 4.14.221-1
> kmod-fs-nfs - 4.14.221-1
> kmod-fs-nfs-common - 4.14.221-1
> kmod-fs-vfat - 4.14.221-1
> kmod-gpio-button-hotplug - 4.14.221-3
> kmod-hwmon-core - 4.14.221-1
> kmod-ip6tables - 4.14.221-1
> kmod-ipt-conntrack - 4.14.221-1
> kmod-ipt-core - 4.14.221-1
> kmod-ipt-nat - 4.14.221-1
> kmod-ipt-offload - 4.14.221-1
> kmod-leds-gpio - 4.14.221-1
> kmod-ledtrig-default-on - 4.14.221-1
> kmod-ledtrig-netdev - 4.14.221-1
> kmod-ledtrig-timer - 4.14.221-1
> kmod-lib-crc-ccitt - 4.14.221-1
> kmod-lib-crc16 - 4.14.221-1
> kmod-mac80211 - 4.14.221+4.19.161-1-1
> kmod-mt76-core - 4.14.221+2021-02-15-5c768dec-1
> kmod-mt76-usb - 4.14.221+2021-02-15-5c768dec-1
> kmod-mt76x02-common - 4.14.221+2021-02-15-5c768dec-1
> kmod-mt76x02-usb - 4.14.221+2021-02-15-5c768dec-1
> kmod-mt76x2-common - 4.14.221+2021-02-15-5c768dec-1
> kmod-mt76x2u - 4.14.221+2021-02-15-5c768dec-1
> kmod-nf-conntrack - 4.14.221-1
> kmod-nf-conntrack6 - 4.14.221-1
> kmod-nf-flow - 4.14.221-1
> kmod-nf-ipt - 4.14.221-1
> kmod-nf-ipt6 - 4.14.221-1
> kmod-nf-nat - 4.14.221-1
> kmod-nf-nathelper - 4.14.221-1
> kmod-nf-reject - 4.14.221-1
> kmod-nf-reject6 - 4.14.221-1
> kmod-nls-base - 4.14.221-1
> kmod-nls-cp437 - 4.14.221-1
> kmod-nls-iso8859-1 - 4.14.221-1
> kmod-nls-utf8 - 4.14.221-1
> kmod-phy-ath79-usb - 4.14.221-1
> kmod-ppp - 4.14.221-1
> kmod-pppoe - 4.14.221-1
> kmod-pppox - 4.14.221-1
> kmod-rt2800-lib - 4.14.221+4.19.161-1-1
> kmod-rt2800-usb - 4.14.221+4.19.161-1-1
> kmod-rt2x00-lib - 4.14.221+4.19.161-1-1
> kmod-rt2x00-usb - 4.14.221+4.19.161-1-1
> kmod-rtl8187 - 4.14.221+4.19.161-1-1
> kmod-scsi-core - 4.14.221-1
> kmod-scsi-generic - 4.14.221-1
> kmod-slhc - 4.14.221-1
> kmod-usb-core - 4.14.221-1
> kmod-usb-ehci - 4.14.221-1
> kmod-usb-ledtrig-usbport - 4.14.221-1
> kmod-usb-ohci - 4.14.221-1
> kmod-usb-storage - 4.14.221-1
> kmod-usb-storage-extras - 4.14.221-1
> kmod-usb-uhci - 4.14.221-1
> kmod-usb2 - 4.14.221-1
> libatomic1 - 7.5.0-2
> libblkid1 - 2.34-1
> libblobmsg-json - 2020-05-25-66195aee-1
> libbz2-1.0 - 1.0.8-1
> libc - 1.1.24-2
> libcomerr0 - 1.44.5-2
> libcurl4 - 7.66.0-3
> libelf1 - 0.177-1
> libext2fs2 - 1.44.5-2
> libffi - 3.3-2
> libgcc1 - 7.5.0-2
> libgdbm - 1.11-1
> libgmp10 - 6.1.2-2
> libiconv-full2 - 1.11.1-4
> libip4tc2 - 1.8.3-1
> libip6tc2 - 1.8.3-1
> libiwinfo20181126 - 2019-10-16-07315b6f-1
> libjson-c2 - 0.12.1-3.1
> libjson-script - 2020-05-25-66195aee-1
> libltdl7 - 2.4.6-2
> libmbedtls12 - 2.16.12-1
> libncurses6 - 6.1-5
> libnet-1.2.x - 1.2-rc3-4
> libnl-core200 - 3.4.0-2
> libnl-genl200 - 3.4.0-2
> libnl-nf200 - 3.4.0-2
> libnl-route200 - 3.4.0-2
> libnl-tiny - 0.1-5
> libnl200 - 3.4.0-2
> libopenssl-conf - 1.1.1n-1
> libopenssl1.1 - 1.1.1n-1
> libpcap1 - 1.9.1-2.1
> libpcre - 8.43-1
> libpthread - 1.1.24-2
> libreadline8 - 8.0-1
> librt - 1.1.24-2
> libsqlite3-0 - 3310100-1
> libss2 - 1.44.5-2
> libstdcpp6 - 7.5.0-2
> libubox20191228 - 2020-05-25-66195aee-1
> libubus20191227 - 2019-12-27-041c9d1c-1
> libubus20210603 - 2022-02-21-b32a0e17-1
> libuci20130104 - 2019-09-01-415f9e48-4
> libuclient20160123 - 2020-06-17-51e16ebf-1
> libusb-1.0-0 - 1.0.22-2
> libustream-openssl20150806 - 2020-03-13-40b563b1-1
> libuuid1 - 2.34-1
> libxml2 - 2.9.9-3
> libxtables12 - 1.8.3-1
> logd - 2019-06-16-4df34a4d-4
> macchanger - 1.7.0-3
> mtd - 24
> nano - 6.2-1
> ncat - 7.70-1
> netcat - 0.7.1-1
> netifd - 2021-01-09-753c351b-1
> nginx - 1.17.7-3
> odhcp6c - 2021-01-09-64e1b4e7-16
> openssh-client - 8.0p1-1
> openssh-keygen - 8.0p1-1
> openssh-server - 8.0p1-1
> openssh-sftp-server - 8.0p1-1
> openssl-util - 1.1.1n-1
> openwrt-keyring - 2021-02-20-49283916-2
> opkg - 2021-01-31-c5dccea9-1
> php7 - 7.2.34-4
> php7-cgi - 7.2.34-4
> php7-fpm - 7.2.34-4
> php7-mod-hash - 7.2.34-4
> php7-mod-json - 7.2.34-4
> php7-mod-mbstring - 7.2.34-4
> php7-mod-openssl - 7.2.34-4
> php7-mod-session - 7.2.34-4
> php7-mod-sockets - 7.2.34-4
> php7-mod-sqlite3 - 7.2.34-4
> ppp - 2.4.7.git-2019-05-25-3
> ppp-mod-pppoe - 2.4.7.git-2019-05-25-3
> procd - 2020-03-07-09b9bd82-1
> procps-ng - 3.3.15-2
> procps-ng-pkill - 3.3.15-2
> procps-ng-ps - 3.3.15-2
> python-base - 2.7.18-3
> python-codecs - 2.7.18-3
> python-light - 2.7.18-3
> python-logging - 2.7.18-3
> python-openssl - 2.7.18-3
> python-sqlite3 - 2.7.18-3
> rt2800-usb-firmware - 20190416-1
> ssmtp - 2.64-7
> swconfig - 12
> tcpdump-mini - 4.9.3-3
> terminfo - 6.1-5
> uboot-envtools - 2018.03-3.1
> ubox - 2019-06-16-4df34a4d-4
> ubus - 2022-02-21-b32a0e17-1
> ubusd - 2022-02-21-b32a0e17-1
> uci - 2019-09-01-415f9e48-4
> uclibcxx - 0.2.5-3
> uclient-fetch - 2020-06-17-51e16ebf-1
> urandom-seed - 1.0-1
> urngd - 2020-01-21-c7f7b6b6-1
> usb-modeswitch - 2017-12-19-f40f84c2-2
> usbreset - 5
> usbutils - 007-10
> usign - 2020-05-23-f1f65026-1
> wget - 1.20.3-4
> wireless-regdb - 2021.08.28-1
> wireless-tools - 29-6
> wpad - 2019-08-08-ca8c2bd2-8
> zlib - 1.2.11-4
> zoneinfo-core - 2020c-1
> 

[archer-d50-v1-squashfs-sysupgrade.zip](https://github.com/xchwarze/wifi-pineapple-cloner/files/11227819/archer-d50-v1-squashfs-sysupgrade.zip)

**Comment by xchwarze** [comment]
Already answered in the thread you left under "questions".

**Comment by logm1lo** [comment]
> Already answered in the thread you left under "questions".

um.... Could you tell me what thread were you mention?
