### ISSUE TITLE
missing libubus20191227 in imagebuilder

### ISSUE THREAD

**Issue by xchwarze** [xchwarze/wifi-pineapple-cloner#6]
for fix this error download [libubus20191227](https://archive.openwrt.org/releases/19.07.7/packages/mips_24kc/base/libubus20191227_2019-12-27-041c9d1c-1_mips_24kc.ipk)  to local packages folder and edit "Packages" file with this

```
Package: libubus20191227
Version: 2019-12-27-041c9d1c-1
Depends: libc, libubox20191228
Provides: libubus
License: LGPL-2.1
Section: libs
Architecture: mips_24kc
Installed-Size: 9161
Filename: libubus20191227_2019-12-27-041c9d1c-1_mips_24kc.ipk
Size: 9954
SHA256sum: 2fe197ef7d8e260c7df79f00e91a37e4c0ddf215f73c0d26087536cb2f2fb906
Description:  OpenWrt RPC client library
```

**Comment by brightplastik** [comment]
Thank you very much! I saw that before tinkering, and it became useful as soon as I progressed in the guide!

**Comment by xchwarze** [comment]
Fixes candidates:

```
# dont work anymore...!
sed -i 's/downloads.openwrt.org/archive.openwrt.org/' repositories.conf
```

```
# tested ok!
wget https://archive.openwrt.org/releases/19.07.7/packages/mips_24kc/base/libubus20191227_2019-12-27-041c9d1c-1_mips_24kc.ipk -O packages/libubus20191227_2019-12-27-041c9d1c-1_mips_24kc.ipk
```

**Comment by brightplastik** [comment]
Sorry to see someone behaves badly, master. Rest assured your contributes to the cause are invaluable. Nobody can steal the intellect. 😉

**Comment by xchwarze** [comment]
thanks pal!
In a few minutes I will post something that may be useful to you (ง ͡ʘ ͜ʖ ͡ʘ)ง
