### ISSUE TITLE
Building for supported 8MB flash devices - [TP-Link WR1043ND v3]

### ISSUE THREAD

**Issue by logm1lo** [xchwarze/wifi-pineapple-cloner#68]
### Discussed in https://github.com/xchwarze/wifi-pineapple-cloner/discussions/67

<div type='discussions-op-text'>

<sup>Originally posted by **logm1lo** May 29, 2023</sup>
First of all thank you for this interesting project!

So when I try to compile an image for my WR1043ND v3 it return me an error "file-system partition is too big", so I've made a custom build and kept only the minimum packages to mount the usb drive at booting :

`make image PROFILE=tplink_tl-wr1043nd-v3 PACKAGES="iw at autossh bash block-mount ca-certificates hostapd-utils kmod-fs-ext4 kmod-fs-nfs kmod-fs-vfat kmod-gpio-button-hotplug kmod-ipt-offload kmod-leds-gpio kmod-ledtrig-default-on kmod-ledtrig-netdev kmod-ledtrig-timer kmod-mt76x2u kmod-nf-nathelper kmod-scsi-generic kmod-usb-acm kmod-usb-net-asix kmod-usb-net-asix-ax88179 kmod-usb-net-qmi-wwan kmod-usb-net-rndis kmod-usb-net-sierrawireless kmod-usb-net-smsc95xx kmod-usb-ohci kmod-usb-storage-extras kmod-usb-uhci kmod-usb2 openssh-server openssh-sftp-server libatomic1 libstdcpp6 libustream-mbedtls20150806 uboot-envtools uci uclibcxx uclient-fetch usb-modeswitch usbreset usbutils wget wireless-tools wpad busybox libatomic1 libstdcpp6 zram-swap -wpad-basic -dropbear -odhcpd-ipv6only -ppp -ppp-mod-pppoe " FILES=../rootfs`

and install the rest after with : service wpc-tools missing_packages

The problem here is that when I try to access the web interface http://172.16.42.1:1471/ on both web browsers **Chrome** and **Opera GX** I get this error : 

"ERR_CONNECTION_REFUSED"
<img width="586" alt="image" src="https://github.com/xchwarze/wifi-pineapple-cloner/assets/55241926/6dd35515-07ba-485a-96a4-15cab1c24862">
<img width="990" alt="image" src="https://github.com/xchwarze/wifi-pineapple-cloner/assets/55241926/cfac25ab-3e3e-4988-b110-4919a32edcb5">

I've uploaded the compiled image below this:
[tplink_tl-wr1043nd-v3-pineapple-tetra-minimal.zip](https://github.com/xchwarze/wifi-pineapple-cloner/files/11588521/tplink_tl-wr1043nd-v3-pineapple-tetra-minimal.zip)

_I've been able to resolve the above issue_

**But I still have a question about which php and nginx file do I need to modify?**
<img width="394" alt="image" src="https://github.com/xchwarze/wifi-pineapple-cloner/assets/55241926/f833602c-7714-4291-a3e7-8d14761fe824">
<img width="400" alt="image" src="https://github.com/xchwarze/wifi-pineapple-cloner/assets/55241926/7003f580-ea1b-43fe-b387-4848ae055b37">
<img width="391" alt="image" src="https://github.com/xchwarze/wifi-pineapple-cloner/assets/55241926/f7ccd7c1-56a2-40c4-b9da-a25c9f98ad07">

**and also, I am able to access webgui after only install the essential packages relate to usb and network:**
`make image PROFILE=tplink_tl-wr1043nd-v3 PACKAGES="block-mount ca-certificates dnsmasq ethtool ip6tables iw kmod-fs-ext4 kmod-gpio-button-hotplug kmod-ipt-offload kmod-leds-gpio kmod-ledtrig-default-on kmod-ledtrig-netdev kmod-ledtrig-timer kmod-mt76x2u kmod-nf-nathelper kmod-rt2800-usb kmod-rtl8187 kmod-scsi-generic kmod-usb-ohci kmod-usb-storage-extras kmod-usb-uhci kmod-usb2 libcurl4 libustream-mbedtls20150806 mtd nano nginx openssh-client openssh-server openssh-sftp-server openssl-util ppp procps-ng-pkill procps-ng-ps tcpdump-mini uci uclibcxx uclient-fetch urngd usb-modeswitch usbreset usbutils wireless-tools wpad-mini busybox -wpad-basic -dropbear -odhcpd-ipv6only -ppp -ppp-mod-pppoe" FILES=../rootfs`

**but still, no modules available to use**
<img width="995" alt="image" src="https://github.com/xchwarze/wifi-pineapple-cloner/assets/55241926/bbdc6f80-3b34-4ea5-83f2-bbcf6304aeb2">

Thanks for your time!</div>

**Comment by xchwarze** [comment]
you have to do these steps:
1. you have to make a minimal build in charge of having the configs and mount the usb.
2. Edit the script that installs the missing dependencies so that it installs all the ones you deleted extra in the previous step.
3. You may have to make a syslink so that nginx/php that are installed on SD/USB can read the configs. You may have to do some more editing.

As I don't have a router to test something like this I can't replicate the steps to tell you what might go wrong, but if you follow these points to the letter you should be able to do it.

**Comment by xchwarze** [comment]
please use https://github.com/xchwarze/wifi-pineapple-cloner/discussions/67
