### ISSUE TITLE
please make it for armv8

### ISSUE THREAD

**Issue by R1punk** [xchwarze/wifi-pineapple-cloner#7]
can this method be applied to openwrt amlogic s905x armv8?

please answer, so I'm not curious .

**Comment by xchwarze** [comment]
The short answer is no.

But if you still want to do it:
1) decompile pineap and pinepd and with some work you could make a cross-platform equivalent
2) do the same with karma patches

Once you have solved those two points you could do it.
I don't know how much work it would be, maybe 20 hours, although it could end up being more than 200 hours ...

**Comment by R1punk** [comment]
ok thx bro 👍
